# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='content',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
