# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 07:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0003_person_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='publish_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
