# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0004_auto_20170301_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='publish_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
